LABELS = {
    'S01': {'risk_level': 0, 'risk_label': 'Safe',     'exploitability': 0.0, 'blast_radius': 0.0},
    'S02': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.2, 'blast_radius': 0.3},
    'S03': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.3, 'blast_radius': 0.2},
    'S04': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.1, 'blast_radius': 0.1},
    'S05': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.3, 'blast_radius': 0.6},
    'S06': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.4, 'blast_radius': 0.6},
    'S07': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.5, 'blast_radius': 0.4},
    'S08': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.3, 'blast_radius': 0.5},
    'S09': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.6, 'blast_radius': 0.7},
    'S10': {'risk_level': 3, 'risk_label': 'High', 'exploitability': 0.7, 'blast_radius': 0.7},
    'S11': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.9, 'blast_radius': 0.9},
    'S12': {'risk_level': 3, 'risk_label': 'High', 'exploitability': 0.6, 'blast_radius': 0.8},
    'S13': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.8, 'blast_radius': 0.9},
    'S14': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 1.0, 'blast_radius': 1.0},
    'S15': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.85, 'blast_radius': 0.9},
    'S16': {'risk_level': 2, 'risk_label': 'Medium', 'exploitability': 0.3, 'blast_radius': 0.5},
    'S17': {'risk_level': 2, 'risk_label': 'Medium', 'exploitability': 0.4, 'blast_radius': 0.3},
    'S18': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.75, 'blast_radius': 0.8},
    'S19': {'risk_level': 1, 'risk_label': 'Low', 'exploitability': 0.15, 'blast_radius': 0.2},
    'S20': {'risk_level': 0, 'risk_label': 'Safe', 'exploitability': 0.0, 'blast_radius': 0.0},
    'S21': {'risk_level': 2, 'risk_label': 'Medium', 'exploitability': 0.4, 'blast_radius': 0.5},
    'S22': {'risk_level': 1, 'risk_label': 'Low', 'exploitability': 0.25, 'blast_radius': 0.2},
    'S23': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.85, 'blast_radius': 0.9},
    'S24': {'risk_level': 1, 'risk_label': 'Low', 'exploitability': 0.3, 'blast_radius': 0.2},
    'S25': {'risk_level': 3, 'risk_label': 'High', 'exploitability': 0.65, 'blast_radius': 0.7},
    'S26': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.2,  'blast_radius': 0.4},
    'S27': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.1,  'blast_radius': 0.3},
    'S28': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.4,  'blast_radius': 0.5},
    'S29': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.65, 'blast_radius': 0.75},
    'S30': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.9,  'blast_radius': 0.95},
    'S31': {'risk_level': 0, 'risk_label': 'Safe',     'exploitability': 0.0,  'blast_radius': 0.0},
    'S32': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.85, 'blast_radius': 1.0},
    'S33': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.95, 'blast_radius': 1.0},
    'S34': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.1,  'blast_radius': 0.2},
    'S35': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.7,  'blast_radius': 0.85},
    'S36': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.6,  'blast_radius': 0.9},
    'S37': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.65, 'blast_radius': 0.85},
    'S38': {'risk_level': 0, 'risk_label': 'Safe',     'exploitability': 0.0,  'blast_radius': 0.0},
    'S39': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.35, 'blast_radius': 0.6},
    'S40': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.2,  'blast_radius': 0.2},
    'S41': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.95, 'blast_radius': 0.95},
    'S42': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.25, 'blast_radius': 0.2},
    'S43': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.4,  'blast_radius': 0.3},
    'S44': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.6,  'blast_radius': 0.7},
    'S45': {'risk_level': 0, 'risk_label': 'Safe',     'exploitability': 0.0,  'blast_radius': 0.0},
    'S46': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.45, 'blast_radius': 0.3},
    'S47': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.15, 'blast_radius': 0.25},
    'S48': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.95, 'blast_radius': 0.95},
    'S49': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.35, 'blast_radius': 0.55},
    'S50': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.1,  'blast_radius': 0.2},
    'S51': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.9,  'blast_radius': 0.9},
    'S52': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.3,  'blast_radius': 0.5},
    'S53': {'risk_level': 1, 'risk_label': 'Low',      'exploitability': 0.15, 'blast_radius': 0.3},
    'S54': {'risk_level': 0, 'risk_label': 'Safe',     'exploitability': 0.0,  'blast_radius': 0.0},
    'S55': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 0.88, 'blast_radius': 0.9},
    'S56': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.72, 'blast_radius': 0.8},
    'S57': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 1.0,  'blast_radius': 1.0},
    'S58': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.4,  'blast_radius': 0.5},
    'S59': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.75, 'blast_radius': 0.8},
    'S60': {'risk_level': 2, 'risk_label': 'Medium',   'exploitability': 0.35, 'blast_radius': 0.45},
    'S61': {'risk_level': 3, 'risk_label': 'High',     'exploitability': 0.65, 'blast_radius': 0.75},
    'S62': {'risk_level': 4, 'risk_label': 'Critical', 'exploitability': 1.0,  'blast_radius': 1.0},
}


import pandas as pd

df = pd.read_csv('dataset/features_combined.csv')

for col in ['risk_level', 'risk_label', 'exploitability', 'blast_radius']:
    df[col] = df['scenario_id'].map(lambda sid: LABELS.get(sid, {}).get(col, None))

df.to_csv('dataset/labeled_dataset.csv', index=False)
print('Labeled dataset saved: dataset/labeled_dataset.csv')
print(df[['scenario_id', 'risk_label', 'exploitability', 'blast_radius']].to_string())